import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/custom/Header";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import Refresher from "@/components/custom/refresher";
import QueryProvider from "./query-provider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("min-h-screen bg-background antialiased", manrope.variable)}
    >
      <StoreProvider>
        <body className="min-h-full flex flex-col">
          <QueryProvider>
            <Refresher>
              <Header />
              <main>{children}</main>
              <Toaster />
            </Refresher>
          </QueryProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
